/**
 * API Response Types
 * ==================
 * Auto-generated from actual API responses
 * Generated: 2025-11-12T14:28:00.582Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate:types
 */


/**
 * Base API Response Structure
 */
export interface BaseApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

/**
 * Paginated Response Structure
 */
export interface PaginatedResponse<T = any> {
  success: boolean;
  data: T[];
  pagination: {
    total: number;
    limit: number;
    offset: number;
    current_page: number;
    total_pages: number;
    has_next_page: boolean;
    has_prev_page: boolean;
  };
}


/**
 * Response from searching fiches by date with status
 * (Error type - endpoint failed during testing)
 */
export type FicheSearchResponse = {
  success: false;
  error: string;
  message?: string;
};


/**
 * Response from getting fiche details with recordings
 * (Generic type - no test data available)
 */
export type FicheDetailsResponse = BaseApiResponse<any>;


/**
 * Response from refreshing fiche details from API
 * (Generic type - no test data available)
 */
export type FicheDetailsRefreshResponse = BaseApiResponse<any>;


/**
 * Response from getting cached fiche data
 * (Generic type - no test data available)
 */
export type FicheCacheResponse = BaseApiResponse<any>;


/**
 * Response from getting fiche transcription and audit status
 * (Generic type - no test data available)
 */
export type FicheStatusResponse = BaseApiResponse<any>;


/**
 * Response from getting status for multiple fiches
 */
export type FichesBatchStatusResponse = {
  success: boolean;
  data: {
  "1753254": {
  ficheId: string;
  hasData: boolean;
  transcription: {
  total: number;
  transcribed: number;
  pending: number;
  percentage: number;
  isComplete: boolean;
  lastTranscribedAt?: null;
};
  audit: {
  total: number;
  completed: number;
  pending: number;
  running: number;
  compliant: number;
  nonCompliant: number;
  averageScore?: null;
  latestAudit?: null;
};
};
  "1762209": {
  ficheId: string;
  hasData: boolean;
  transcription: {
  total: number;
  transcribed: number;
  pending: number;
  percentage: number;
  isComplete: boolean;
  lastTranscribedAt?: null;
};
  audit: {
  total: number;
  completed: number;
  pending: number;
  running: number;
  compliant: number;
  nonCompliant: number;
  averageScore?: null;
  latestAudit?: null;
};
};
};
};


/**
 * Response from getting all fiches for a specific date with status
 */
export type FichesByDateResponse = {
  success: boolean;
  data: {
  date: string;
  total: number;
  fiches: any[];
};
};


/**
 * Response from getting fiches for a date range with status
 */
export type FichesByDateRangeResponse = {
  success: boolean;
  data: {
  startDate: string;
  endDate: string;
  total: number;
  fiches: any[];
};
};


/**
 * Response from getting all recordings for a fiche
 * (Generic type - no test data available)
 */
export type RecordingsListResponse = BaseApiResponse<any>;


/**
 * Response from queueing a transcription job
 */
export type TranscriptionQueueResponse = {
  success: boolean;
  message: string;
  fiche_id: string;
  event_id: string;
};


/**
 * Response from getting transcription status for a fiche
 * (Generic type - no test data available)
 */
export type TranscriptionStatusResponse = BaseApiResponse<any>;


/**
 * Response from getting transcription for a specific recording
 * (Generic type - no test data available)
 */
export type RecordingTranscriptionResponse = BaseApiResponse<any>;


/**
 * Response from queueing multiple transcription jobs
 */
export type TranscriptionBatchQueueResponse = {
  success: boolean;
  message: string;
  fiche_id: string;
  event_id: string;
};


/**
 * Response from listing all audits with filtering and pagination
 */
export type AuditsListResponse = {
  success: boolean;
  data: {
  id: string;
  ficheCacheId: string;
  auditConfigId: string;
  overallScore: string;
  scorePercentage: string;
  niveau: string;
  isCompliant: boolean;
  criticalPassed: number;
  criticalTotal: number;
  status: string;
  startedAt: string;
  completedAt: string;
  durationMs: number;
  errorMessage?: null;
  totalTokens: number;
  successfulSteps: number;
  failedSteps: number;
  recordingsCount: number;
  timelineChunks: number;
  resultData: {
  audit: {
  fiche: {
  groupe: any;
  fiche_id: any;
  prospect_name: any;
};
  config: {
  id: any;
  name: any;
  description: any;
};
  results: {
  steps: any;
  compliance: any;
};
  compliance: {
  score: any;
  niveau: any;
  poids_total: any;
  poids_obtenu: any;
  points_critiques: any;
};
};
  metadata: {
  started_at: string;
  duration_ms: number;
  completed_at: string;
};
  statistics: {
  failed_steps: number;
  total_tokens: number;
  timeline_chunks: number;
  recordings_count: number;
  successful_steps: number;
  total_time_seconds: number;
  transcriptions_count: number;
};
};
  version: number;
  isLatest: boolean;
  createdAt: string;
  updatedAt: string;
  ficheCache: {
  ficheId: string;
  groupe: string;
  prospectNom: string;
  prospectPrenom: string;
};
  auditConfig: {
  id: string;
  name: string;
  description: string;
};
}[];
  pagination: {
  total: number;
  limit: number;
  offset: number;
  current_page: number;
  total_pages: number;
  has_next_page: boolean;
  has_prev_page: boolean;
};
};


/**
 * Response from listing audits with filters applied
 */
export type AuditsListFilteredResponse = {
  success: boolean;
  data: any[];
  pagination: {
  total: number;
  limit: number;
  offset: number;
  current_page: number;
  total_pages: number;
  has_next_page: boolean;
  has_prev_page: boolean;
};
};


/**
 * Response from getting audits grouped by fiches
 */
export type AuditsGroupedByFichesResponse = {
  success: boolean;
  data: {
  fiche: {
  id: string;
  ficheId: string;
  groupe: string;
  agenceNom: string;
  prospectNom: string;
  prospectPrenom: string;
  prospectEmail: string;
  prospectTel: string;
  hasRecordings: boolean;
  recordingsCount: number;
  fetchedAt: string;
  createdAt: string;
  updatedAt: string;
};
  audits: {
  id: string;
  ficheCacheId: string;
  auditConfigId: string;
  overallScore: string;
  scorePercentage: string;
  niveau: string;
  isCompliant: boolean;
  criticalPassed: number;
  criticalTotal: number;
  status: string;
  startedAt: string;
  completedAt: string;
  durationMs: number;
  errorMessage?: null;
  totalTokens: number;
  successfulSteps: number;
  failedSteps: number;
  recordingsCount: number;
  timelineChunks: number;
  resultData: {
  audit: any;
  metadata: any;
  statistics: any;
};
  version: number;
  isLatest: boolean;
  createdAt: string;
  updatedAt: string;
  auditConfig: {
  id: any;
  name: any;
  description: any;
};
  stepResults: any[];
}[];
  summary: {
  totalAudits: number;
  compliantCount: number;
  averageScore: number;
  latestAuditDate: string;
};
}[];
  pagination: {
  total: number;
  limit: number;
  offset: number;
  current_page: number;
  total_pages: number;
  has_next_page: boolean;
  has_prev_page: boolean;
};
};


/**
 * Response from getting detailed audit results
 * (Generic type - no test data available)
 */
export type AuditDetailsResponse = BaseApiResponse<any>;


/**
 * Response from getting audit history for a fiche
 */
export type AuditsByFicheResponse = {
  success: boolean;
  data: any[];
  count: number;
};


/**
 * Response from queuing an audit job
 */
export type AuditRunResponse = {
  success: boolean;
  message: string;
  event_id: string;
  fiche_id: string;
  audit_config_id: number;
  metadata: {
  timestamp: string;
  status: string;
};
};


/**
 * Response from queuing audit with latest config
 */
export type AuditRunLatestResponse = {
  success: boolean;
  message: string;
  event_id: string;
  fiche_id: string;
  audit_config_id: string;
  audit_config_name: string;
  metadata: {
  timestamp: string;
  status: string;
};
};


/**
 * Response from batch queuing audits
 */
export type AuditBatchRunResponse = {
  success: boolean;
  message: string;
  fiche_ids: string[];
  audit_config_id: number;
  batch_id: string;
  event_ids: string[];
};


/**
 * Response from listing all audit configurations
 */
export type AuditConfigsListResponse = {
  success: boolean;
  data: {
  id: string;
  name: string;
  description: string;
  systemPrompt: string;
  isActive: boolean;
  stepsCount: number;
  createdAt: string;
  createdBy: string;
  steps: {
  id: string;
  name: string;
  position: number;
  severityLevel: string;
  isCritical: boolean;
  weight: number;
  chronologicalImportant: boolean;
  verifyProductInfo: boolean;
  controlPoints: any[];
  keywords: any[];
}[];
}[];
  count: number;
};


/**
 * Response from getting audit configuration details
 * (Generic type - no test data available)
 */
export type AuditConfigDetailsResponse = BaseApiResponse<any>;


/**
 * Response from creating audit configuration
 */
export type AuditConfigCreateResponse = {
  success: boolean;
  data: {
  id: string;
  name: string;
};
};


/**
 * Response from updating audit configuration
 * (Generic type - no test data available)
 */
export type AuditConfigUpdateResponse = BaseApiResponse<any>;


/**
 * Response from listing automation schedules
 */
export type AutomationSchedulesListResponse = {
  success: boolean;
  data: {
  id: string;
  specificAuditConfigs: any[];
  name: string;
  description: string;
  isActive: boolean;
  createdBy?: null;
  createdAt: string;
  updatedAt: string;
  scheduleType: string;
  cronExpression?: null;
  timezone: string;
  timeOfDay: string;
  dayOfWeek?: null;
  dayOfMonth?: null;
  ficheSelection: {
  mode: string;
  dateRange: string;
  onlyUnaudited: boolean;
  onlyWithRecordings: boolean;
};
  runTranscription: boolean;
  skipIfTranscribed: boolean;
  transcriptionPriority: string;
  runAudits: boolean;
  useAutomaticAudits: boolean;
  continueOnError: boolean;
  retryFailed: boolean;
  maxRetries: number;
  notifyOnComplete: boolean;
  notifyOnError: boolean;
  webhookUrl?: null;
  notifyEmails: any[];
  externalApiKey?: null;
  lastRunAt: string;
  lastRunStatus: string;
  totalRuns: number;
  successfulRuns: number;
  failedRuns: number;
}[];
  count: number;
};


/**
 * Response from getting automation schedule details
 * (Generic type - no test data available)
 */
export type AutomationScheduleDetailsResponse = BaseApiResponse<any>;


/**
 * Response from creating automation schedule
 * (Error type - endpoint failed during testing)
 */
export type AutomationScheduleCreateResponse = {
  success: false;
  error: string;
  message?: string;
};


/**
 * Response from updating automation schedule
 * (Generic type - no test data available)
 */
export type AutomationScheduleUpdateResponse = BaseApiResponse<any>;


/**
 * Response from manually triggering automation
 */
export type AutomationTriggerResponse = {
  success: boolean;
  message: string;
  schedule_id: number;
};


/**
 * Response from getting automation runs
 */
export type AutomationRunsListResponse = {
  success: boolean;
  data: any[];
  count: number;
  limit: number;
  offset: number;
};


/**
 * Response from getting automation run details
 */
export type AutomationRunDetailsResponse = {
  success: boolean;
  data: {
  id: string;
  scheduleId: string;
  status: string;
  startedAt: string;
  completedAt?: null;
  durationMs?: null;
  totalFiches: number;
  successfulFiches: number;
  failedFiches: number;
  transcriptionsRun: number;
  auditsRun: number;
  errorMessage?: null;
  errorDetails?: null;
  configSnapshot: {
  schedule: {
  name: string;
  scheduleType: string;
};
  overrides?: null;
};
  resultSummary?: null;
  logs: any[];
};
};


/**
 * Response from getting automation run logs
 */
export type AutomationRunLogsResponse = {
  success: boolean;
  data: any[];
  count: number;
};


/**
 * Response from getting audit chat history
 * (Generic type - no test data available)
 */
export type AuditChatHistoryResponse = BaseApiResponse<any>;


/**
 * Response from getting fiche chat history
 */
export type FicheChatHistoryResponse = {
  success: boolean;
  data: {
  conversationId: string;
  ficheId: string;
  messages: any[];
  messageCount: number;
};
};


/**
 * Response from testing webhook delivery
 */
export type WebhookTestResponse = {
  success: boolean;
  eventType: string;
  delivered: boolean;
  message: string;
};


/**
 * Response from testing all webhook types
 */
export type WebhookTestAllResponse = {
  success: boolean;
  message: string;
  results: {
  "audit.started": boolean;
  "audit.progress": boolean;
  "audit.completed": boolean;
  "audit.failed": boolean;
  "transcription.progress": boolean;
  "transcription.completed": boolean;
  "batch.progress": boolean;
  "batch.completed": boolean;
  notification: boolean;
};
};


/**
 * Response from starting webhook workflow simulation
 */
export type WebhookWorkflowTestResponse = {
  success: boolean;
  message: string;
  auditId: string;
  steps: number;
  estimatedDuration: string;
};


/**
 * Response from health check endpoint
 */
export type HealthCheckResponse = {
  status: string;
  timestamp: string;
  service: string;
  version: string;
};



/**
 * Helper Types
 */

// Chat streaming chunk types
export interface ChatTextChunk {
  text: string;
}

export interface ChatCitationsChunk {
  citations: Array<{
    text: string;
    source: string;
    timestamp?: string;
  }>;
}

export type ChatStreamChunk = ChatTextChunk | ChatCitationsChunk | { error: string } | "[DONE]";

// Webhook event types
export type WebhookEventType =
  | "audit.started"
  | "audit.progress"
  | "audit.completed"
  | "audit.failed"
  | "transcription.progress"
  | "transcription.completed"
  | "batch.progress"
  | "batch.completed"
  | "notification";

// Status types
export type AuditStatus = "pending" | "running" | "completed" | "failed";
export type RecordingStatus = "pending" | "transcribed" | "failed";
export type AutomationStatus = "pending" | "running" | "completed" | "failed";

// Date types
export type ISODateString = string;
export type ISODateTimeString = string;
